---
- name: Déploiement de la stack LAMP
  hosts: all
  become: yes
  roles:
    - { role: apache_php, when: "'web' in group_names" }
    - { role: mariadb,    when: "'database' in group_names" }
    - { role: bind9,      when: "'dns' in group_names" }
    - { role: wordpress,  when: "'web' in group_names" }
